import {
  Banner,
  Code,
  Em,
  H2,
  H3,
  InlineImage,
  LI,
  P,
  Strong,
  Table,
  UL,
} from "@/components/blog/Prose";

const POST_IMAGE =
  "/images/blog/how-to-calculate-apple-search-ads-roas-with-revenuecat/how-to-calculate-apple-search-ads-roas-with-revenuecat.png";

export function CalculateRoasRevenueCatBody() {
  return (
    <>
      <P>
        If you&rsquo;re running Apple Search Ads and using RevenueCat for
        subscription management, you&rsquo;re sitting on everything you need to
        calculate true ROAS. The problem is, most developers never connect the
        two properly &mdash; and end up optimizing based on installs instead of
        revenue.
      </P>
      <P>
        This guide walks through exactly how to calculate Apple Search Ads ROAS
        using RevenueCat, what the numbers actually mean for subscription apps,
        and where the process breaks down at scale.
      </P>

      <H2>What ROAS Actually Means for a Subscription App</H2>
      <P>
        ROAS stands for Return on Ad Spend. The basic formula is straightforward:
      </P>
      <P>
        <Strong>ROAS = Revenue &divide; Ad Spend</Strong>
      </P>
      <P>
        If you spent $1,000 on Apple Search Ads and the users you acquired
        generated $1,200 in subscription revenue, your ROAS is 1.2x (or 120%).
      </P>
      <P>
        But here&rsquo;s where subscription apps differ from one-time purchase
        apps: the revenue doesn&rsquo;t arrive all at once. A user who downloads
        your app today might trial for 7 days, convert to a monthly
        subscription, and renew 6 times over the next 6 months. Your true ROAS
        only becomes visible over time.
      </P>
      <P>This is why you need to think about ROAS in time windows:</P>
      <UL>
        <LI>
          <Strong>Day-7 ROAS</Strong>{" "}&mdash; Did the trial convert? Is ad spend
          covered?
        </LI>
        <LI>
          <Strong>Day-30 ROAS</Strong>{" "}&mdash; Did the first billing cycle
          renew?
        </LI>
        <LI>
          <Strong>Day-90 ROAS</Strong>{" "}&mdash; Is this keyword actually
          profitable over a quarter?
        </LI>
      </UL>
      <P>
        Apple Search Ads shows you cost-per-install and taps. RevenueCat tracks
        your subscription lifecycle &mdash; trials, conversions, renewals,
        cancellations, and refunds. Put them together and you have what you
        need.
      </P>

      <H2>How to Calculate ROAS Manually Using RevenueCat + Apple Search Ads</H2>
      <P>
        Here&rsquo;s the process most developers use when they&rsquo;re doing
        this properly.
      </P>

      <H3>Step 1: Pull your spend data from Apple Search Ads</H3>
      <P>
        Log into your Apple Search Ads dashboard and export a campaign report.
        Note your total spend by campaign, date range, and keyword.
      </P>

      <H3>Step 2: Pull revenue attribution from RevenueCat</H3>
      <P>
        By default, RevenueCat labels revenue as &ldquo;Organic&rdquo; or
        &ldquo;Unspecified.&rdquo; Before this step works, you&rsquo;ll need
        attribution set up &mdash; once it is, your campaigns will appear as a
        filter in RevenueCat Charts.
      </P>
      <InlineImage
        src={POST_IMAGE}
        alt="RevenueCat Charts filtered by Apple Search Ads campaign showing revenue attribution"
        width={2438}
        height={1142}
      />
      <P>
        Filter your Revenue chart by your Apple Search Ads campaign and set the
        same date range as your spend export from Step 1. The number you see is
        the subscription revenue attributed to that campaign.
      </P>

      <H3>Step 3: Apply the ROAS formula</H3>
      <Code>ROAS = Revenue from campaign &divide; Spend on campaign</Code>
      <P>
        Example: $2,400 revenue &divide; $2,000 spend ={" "}
        <Strong>1.2x ROAS</Strong>
      </P>
      <P>
        One important detail on the time window: make sure you&rsquo;re looking
        at revenue generated by users <Em>acquired</Em>{" "}in your chosen date
        range &mdash; not all revenue that came in during that period. Total
        revenue mixes in renewals from users acquired months ago, which inflates
        the number and makes your current campaigns look better than they are.
        RevenueCat&rsquo;s cohort view handles this correctly.
      </P>

      <H3>Step 4: Repeat for each time window</H3>
      <P>
        Calculate your Day-7, Day-30, and Day-90 ROAS separately. A keyword
        might look unprofitable at Day-7 but become your best performer by
        Day-90 if renewal rates are strong.
      </P>

      <H2>The Renewal Revenue Factor Nobody Talks About</H2>
      <P>
        Here&rsquo;s something that changes how you should read your early ROAS
        numbers.
      </P>
      <P>
        When you first launch an Apple Search Ads campaign, you&rsquo;re almost
        certainly ROAS negative. You&rsquo;re paying for installs, users are in
        free trial, and no subscription revenue has hit yet. Day-7 ROAS looks
        terrible. You might be tempted to kill the campaign.
      </P>
      <P>
        But subscription apps have a delayed payoff that most ROAS calculations
        miss: renewal revenue.
      </P>
      <P>
        Every user who converts from trial to paid and then renews &mdash; month
        after month &mdash; is generating revenue that traces back to the
        original keyword that acquired them. That renewal revenue is
        non-organic. It came from your ad spend. But it arrives weeks and months
        after the initial install, long after most developers have moved on to
        the next campaign.
      </P>
      <P>What this means in practice:</P>
      <UL>
        <LI>
          A keyword that looks like 0.4x ROAS at Day-7 might be 1.2x by Day-90
          purely from renewals stacking up
        </LI>
        <LI>
          A campaign you were about to pause could be your most profitable one
          &mdash; you just can&rsquo;t see it yet
        </LI>
        <LI>
          Conversely, a keyword with strong Day-7 numbers might churn heavily
          and never reach profitability
        </LI>
      </UL>
      <P>
        This is why the Day-7 / Day-30 / Day-90 windows matter so much.
        You&rsquo;re not just tracking one purchase &mdash; you&rsquo;re
        watching a cohort of users move through their subscription lifecycle
        over time.
      </P>
      <P>
        The honest truth: not every keyword gets there. Some never cross into
        profitability no matter how long you wait. The renewal curve either
        climbs or it doesn&rsquo;t. But you can&rsquo;t know which is happening
        without tracking renewal revenue back to its source &mdash; which
        brings you right back to the keyword attribution problem.
      </P>

      <H3>Step 5: Do it again. And again.</H3>
      <P>
        Same export. Same date range matching. Same cohort filtering. Same
        formula. For every campaign, every week, across every country
        you&rsquo;re running in.
      </P>
      <P>
        This is the part where most developers either give up on this level of
        optimization entirely, or spend their Sunday afternoons in spreadsheets
        instead of building their app.
      </P>
      <P>
        That&rsquo;s the problem AppSkale solves &mdash; not a data problem,
        just the automation of work you&rsquo;d otherwise do by hand.
      </P>

      <H2>The Hidden Problem With Campaign-Level Numbers</H2>
      <P>
        Here&rsquo;s what makes this worth doing even when it&rsquo;s painful:
        campaign-level ROAS hides what&rsquo;s actually happening inside your
        account.
      </P>
      <P>
        Your overall campaign might show 1.47x ROAS and look healthy. But
        underneath, the numbers tell a completely different story.
      </P>
      <P>Take this example from a meditation app running four keywords:</P>
      <Table
        headers={["Keyword", "Monthly Spend", "Revenue (90-day)", "ROAS"]}
        rows={[
          ["meditation app", "$400", "$180", "0.45x"],
          ["sleep sounds", "$300", "$690", "2.3x"],
          ["anxiety relief", "$200", "$540", "2.7x"],
          ["mindfulness", "$100", "$60", "0.6x"],
          [
            <Strong key="t-label">Total</Strong>,
            <Strong key="t-spend">$1,000</Strong>,
            <Strong key="t-rev">$1,470</Strong>,
            <Strong key="t-roas">1.47x</Strong>,
          ],
        ]}
      />
      <P>
        At a glance, 1.47x looks fine. Two keywords are losing money on every
        dollar spent. Two keywords are producing strong returns. The profitable
        ones are carrying the losers &mdash; and unless you do the
        keyword-level math, you&rsquo;d never know.
      </P>
      <P>
        The right move: pause &ldquo;meditation app&rdquo; and
        &ldquo;mindfulness,&rdquo; reallocate $500 to &ldquo;sleep sounds&rdquo;
        and &ldquo;anxiety relief.&rdquo; Same budget. Dramatically higher
        returns.
      </P>
      <P>
        You cannot make this decision with campaign-level data alone. The only
        way to see it is to do the calculation per keyword &mdash; which brings
        you back to the spreadsheet.
      </P>

      <H2>Why This Breaks Down at Scale</H2>
      <P>The manual process works when you&rsquo;re small. It stops working when:</P>
      <UL>
        <LI>You&rsquo;re running 10+ active keywords</LI>
        <LI>You have campaigns across multiple countries</LI>
        <LI>You&rsquo;re optimizing weekly rather than monthly</LI>
        <LI>
          Trial-to-subscription conversions happen days or weeks after the
          original install
        </LI>
      </UL>
      <P>
        At that point, by the time you&rsquo;ve finished your spreadsheet, the
        data is already stale. You&rsquo;ve spent the next week&rsquo;s budget
        on the same keywords that last week&rsquo;s analysis said to cut.
      </P>

      <Banner src={POST_IMAGE} alt="RevenueCat Demo" />
    </>
  );
}
